<?php

namespace Modules\Udemy\Tests;

use Modules\Core\Zeus\ZeusService;
use Modules\Udemy\Services\Client\UdemySdk;
use Modules\Udemy\Zeus\Wishes\UdemyWish;
use Tests\TestCase as BaseTestCase;

class TestCase extends BaseTestCase
{
    protected UdemySdk $udemySdk;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        app(ZeusService::class)->wish(UdemyWish::class);

        $this->udemySdk = app(UdemySdk::class);
    }
}
