<?php

namespace Modules\Udemy\Tests;

use Modules\Core\Zeus\ZeusService;
use Modules\Udemy\Zeus\Wishes\UdemyWish;
use Tests\TestCase as BaseTestCase;

class TestCase extends BaseTestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        app(ZeusService::class)->wish(UdemyWish::class);
    }
}
