# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
name: XCrawlerII - Build & Tests

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize ]
  push:
    branches: [ develop ]

#concurrency:
#  group: staging_build_test_${{ github.head_ref }}
#  cancel-in-progress: true

jobs:

  code_standards:
    name: Code standards check
    strategy:
      matrix:
        lint: [ phpmd, phpstan, pint ]

    runs-on:
      - self-hosted
      - ubuntu

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup application
        if: success()
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          composer install --no-ansi --no-scripts --no-progress --prefer-dist

      - name: Lint
        run: composer ${{ matrix.lint }}

  tests:
    name: Execute UnitTest
    strategy:
      matrix:
        test: [ Core, Client, Jav, Udemy ]
    runs-on:
      - self-hosted
      - ubuntu
    needs: [ code_standards ]

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: xcrawlerii
        ports:
          - 3306:3306

      redis:
        image: redis
        ports:
          - 6379:6379

      mongo:
        image: mongo:bionic
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
